# Generated by Django 3.1.5 on 2022-04-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0002_drawing_path_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drawing',
            name='paths',
        ),
        migrations.AddField(
            model_name='drawing',
            name='points',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='drawing',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='author_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='Path',
        ),
        migrations.DeleteModel(
            name='Point',
        ),
    ]
